server:
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  port: 5000
springdoc:
  version: '@springdoc.version@'
  module: 'ocpp-module'
  swagger-ui:
    use-root-path: true
spring:
  security:
    user:
      name: admin
      password: admin
management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hiberate:
        sql: DEBUG

